sudo: false
language: python
python:
  - '2.7'
  - 'pypy-5.4'

# ucspi-tcp is currently not allowed on travis, so for now we use the binary
# we committed to the repo. That's why we add travis/bin to the PATH
env:
  global:
    - CC=gcc-4.8
    - CXX=g++-4.8
    - export PATH="$PATH:$HOME/bin:$TRAVIS_BUILD_DIR/travis/bin"
    - export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$HOME/lib"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - python-dev
      #- ucspi-tcp # for tcpserver, see the comment above

before_install:
  - openssl aes-256-cbc -K $encrypted_571f1f821904_key -iv $encrypted_571f1f821904_iv -in ./travis/travis.rsa.enc -out ./travis/travis.rsa -d

install:
  - curl -O https://capnproto.org/capnproto-c++-0.5.3.tar.gz
  - tar zxf capnproto-c++-0.5.3.tar.gz
  - cd capnproto-c++-0.5.3
  - ./configure --prefix=$HOME
  - make -j3
  - make install
  - cd ../
  - pip install -U pip # so that we can use wheels
  - pip install tox-travis

script:
  - bash ./travis/clone-benchmarks-repo.sh
  - tox
  - py.test travis
  - bash ./travis/commit-results.sh
